#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

newsParser:
    path: /cron_job/news
    controller: App\Controller\CronjobsController::newsParser

dashboard:
    path: /admin/dashboard
    controller: App\Controller\DashboardController::dashboard

delete_news:
    path: /delete/{id}/news
    controller: App\Controller\DashboardController::delete_news

